services:
  - docker

before_install:
  - docker pull magicjo/learn-rxjs:latest

script:
  - docker run -v $(pwd):/app/src magicjo/learn-rxjs:latest start
  - docker run -v $(pwd):/app/src magicjo/learn-rxjs:latest lint
